version: "3.4"
services:
  web:    
    container_name: aspnet
    build:      
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - migrations       
    ports:
      - "8080:80"
      
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: db
    hostname: db
    
    environment:
      SA_PASSWORD: "TNhan249"
      ACCEPT_EULA: "Y"
    restart: unless-stopped    
    ports:
      - "1433:1433"
    depends_on:
      - migrations
  migrations:
    build: 
      context: .
      dockerfile: Migrations.Dockerfile
