version: "3.4"
services:
  web:    
    container_name: aspnet
    build:      
      context: ./
      dockerfile: Dockerfile
    depends_on: [ mssql ]        
    ports:
      - "8080:80"
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: "Thuphuong26"
      ACCEPT_EULA: "Y"
    restart: unless-stopped    
    ports:
      # So we can access the database
      # From a tool like JetBrains Rider
      # Optional for this demo
      - "1433:1433" 
